[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

[etherscan]
14601 = { key = "${ETHERSCAN_API_KEY}", url = "https://api-testnet.sonicscan.org/api" }
