packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@types/node": ^22.9.3
  "@types/react": "18.3.1"
  "@types/react-dom": "18.3.0"
  "@tanstack/react-query": ^5.66.9
  typescript: 5.5.4
  viem: ^2.29.2
  wagmi: ^2.14.12
  react: "18.3.1"
  react-dom: "18.3.1"
  "icon-sdk-js": "1.5.3"
  "@vitest/coverage-v8": "2.1.9"
  "tsup": "^8.4.0"
  "@changesets/cli": "^2.27.9"
  "@arethetypeswrong/cli": "^0.17.4"
  "vitest": "^2.1.3"
