packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@types/node": ^22.9.3
  "@types/react": "18.3.1"
  "@types/react-dom": "18.3.0"
  "@tanstack/react-query": ^5.66.9
  typescript: 5.5.4
  viem: 2.29.2
  wagmi: ^2.14.12
  react: "18.3.1"
  react-dom: "18.3.1"
  "icon-sdk-js": "1.5.3"
  "@vitest/coverage-v8": "2.1.9"
  "tsup": "^8.4.0"
  "@changesets/cli": "^2.27.9"
  "@arethetypeswrong/cli": "^0.17.4"
  "vitest": "^2.1.3"
  "bignumber.js": "^9.1.2"
  "@mysten/sui": "1.21.2"
  "@mysten/wallet-standard": "0.15.6"
  "@mysten/dapp-kit": "0.14.18"
  "@stellar/stellar-sdk": "12.3.0"
  "@injectivelabs/sdk-ts": "1.16.10"
  "@injectivelabs/networks": "1.16.10"
  "@injectivelabs/ts-types": "1.16.10"
  "@injectivelabs/utils": "1.16.10"
  "@injectivelabs/wallet-base": "1.16.10"
  "@injectivelabs/wallet-core": "1.16.10"
  "@injectivelabs/wallet-strategy": "1.16.10"
  "@injectivelabs/wallet-evm": "1.16.10"
  "@injectivelabs/wallet-cosmos": "1.16.10"
  "@injectivelabs/wallet-private-key": "1.16.10"
  "@solana/spl-token": "0.4.9"
  "@solana/wallet-adapter-base": "0.9.26"
  "@solana/web3.js": "1.98.0"
