import type React from 'react';

export default function DepositInfoStep({ apy }: { apy: string }): React.JSX.Element {
  return (
    <div className="flex flex-col gap-4">
      <div className="flex flex-col gap-2">
        <div className="text-espresso text-(length:--body-super-comfortable) font-bold font-['InterRegular'] leading-[1.4]">
          What happens when I supply WBTC?
        </div>
        <div className="self-stretch text-clay text-(length:--body-comfortable) font-medium font-['InterRegular'] leading-[1.4]">
          Your funds will move to SODAX to start earning. You can manage or withdraw anytime.
        </div>
      </div>

      <div className="self-stretch inline-flex justify-start items-start gap-4">
        <div className="flex-1 pl-4 border-l-2 border-cream-white inline-flex flex-col justify-center items-start gap-1">
          <div className="md:w-40 h-4 justify-start text-espresso text-(length:--body-comfortable) font-bold font-['InterRegular'] leading-[1.4]">
            {apy} Variable APY
          </div>
          <div className="self-stretch justify-start text-clay text-(length:--body-comfortable) font-medium font-['InterRegular'] leading-[1.4]">
            Generated by borrowing and solver execution.
          </div>
        </div>

        <div className="flex-1 pl-4 border-l-2 border-cream-white inline-flex flex-col justify-center items-start gap-1">
          <div className="md:w-40 h-4 justify-start text-espresso text-(length:--body-comfortable) font-bold font-['InterRegular'] leading-[1.4]">
            Withdraw anytime
          </div>
          <div className="self-stretch justify-start text-clay text-(length:--body-comfortable) font-medium font-['InterRegular'] leading-[1.4]">
            No lockups. Use your preferred network.
          </div>
        </div>
      </div>
    </div>
  );
}
