'use client';

import type React from 'react';
import { useState, useMemo } from 'react';
import { Dialog, DialogContent, DialogFooter, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import type { XToken, ChainId } from '@sodax/types';
import { useXAccount, useXBalances } from '@sodax/wallet-sdk-react';
import { useTokenPrice } from '@/hooks/useTokenPrice';
import { formatUnits } from 'viem';
import { formatBalance } from '@/lib/utils';
import { useLiquidity } from '@/hooks/useAPY';
import type { FormatReserveUSDResponse } from '@sodax/sdk';
import { FilePenLine, XIcon } from 'lucide-react';
import { TokenAsset } from '@/components/shared/token-asset';
import { cn } from '@/lib/utils';

interface DepositDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  selectedToken: XToken | null;
  tokens: XToken[];
  formattedReserves?: FormatReserveUSDResponse[];
  isFormattedReservesLoading?: boolean;
}

export default function DepositDialog({
  open,
  onOpenChange,
  selectedToken,
  tokens,
  formattedReserves,
  isFormattedReservesLoading,
}: DepositDialogProps): React.JSX.Element {
  const [currentStep, setCurrentStep] = useState<number>(1);
  const [supplyBalance, setSupplyBalance] = useState<string>('0.1');
  const [isApproved, setIsApproved] = useState<boolean>(false);
  const [isApproving, setIsApproving] = useState<boolean>(false);

  const { address: sourceAddress } = useXAccount(selectedToken?.xChainId);
  const { data: balances } = useXBalances({
    xChainId: selectedToken?.xChainId as ChainId,
    xTokens: selectedToken ? [selectedToken] : [],
    address: sourceAddress,
  });

  const balance = balances?.[selectedToken?.address as string] ?? 0n;
  const { data: tokenPrice } = useTokenPrice(selectedToken as XToken);
  const { apy } = useLiquidity(tokens, formattedReserves, isFormattedReservesLoading);

  const maxValue = useMemo(() => {
    if (!selectedToken || !balance) return 0;
    return Number(formatBalance(formatUnits(balance, selectedToken.decimals), tokenPrice ?? 0));
  }, [balance, selectedToken, tokenPrice]);

  const handleContinue = (): void => {
    if (currentStep < 3) {
      setCurrentStep(currentStep + 1);
    }
  };

  const handleApprove = async (): Promise<void> => {
    setIsApproving(true);
    // TODO: Implement actual approval logic
    await new Promise(resolve => setTimeout(resolve, 2000));
    setIsApproved(true);
    setIsApproving(false);
    setCurrentStep(3);
  };

  const handleDeposit = (): void => {
    // TODO: Implement actual deposit logic
    console.log('Depositing:', supplyBalance);
    onOpenChange(false);
    // Reset state when closing
    setCurrentStep(1);
    setSupplyBalance('');
    setIsApproved(false);
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>): void => {
    const inputValue = e.target.value;
    if (inputValue === '') {
      setSupplyBalance('');
      return;
    }

    const numericValue = Number.parseFloat(inputValue);
    if (Number.isNaN(numericValue)) {
      return;
    }

    const clampedValue = Math.max(0, Math.min(numericValue, maxValue));
    setSupplyBalance(clampedValue.toString());
  };

  const handleMaxClick = (): void => {
    setSupplyBalance(maxValue.toString());
  };

  const handleClose = (): void => {
    onOpenChange(false);
    // Reset state when closing
    setCurrentStep(1);
    setSupplyBalance('');
    setIsApproved(false);
  };

  const renderStep1 = (): React.JSX.Element => {
    return (
      <div className="flex flex-col gap-4">
        <div className="flex flex-col gap-2">
          <div className="text-espresso text-(length:--body-super-comfortable) font-bold font-['InterRegular'] leading-[1.4]">
            What happens when I supply WBTC?
          </div>
          <div className="self-stretch text-clay text-(length:--body-comfortable) font-medium font-['InterRegular'] leading-[1.4]">
            Your funds will move to SODAX to start earning. You can manage or withdraw anytime.
          </div>
        </div>
        <div className="self-stretch inline-flex justify-start items-start gap-4">
          <div className="flex-1 pl-4 border-l-2 border-cream-white inline-flex flex-col justify-center items-start gap-1">
            <div className="md:w-40 h-4 justify-start text-espresso text-(length:--body-comfortable) font-bold font-['InterRegular'] leading-[1.4]">
              Variable interest
            </div>
            <div className="self-stretch justify-start text-clay text-(length:--body-comfortable) font-medium font-['InterRegular'] leading-[1.4]">
              Generated by borrowing and solver execution.
            </div>
          </div>
          <div className="flex-1 pl-4 border-l-2 border-cream-white inline-flex flex-col justify-center items-start gap-1">
            <div className="md:w-40 h-4 justify-start text-espresso text-(length:--body-comfortable) font-bold font-['InterRegular'] leading-[1.4]">
              Withdraw anytime
            </div>
            <div className="self-stretch justify-start text-clay text-(length:--body-comfortable) font-medium font-['InterRegular'] leading-[1.4]">
              No lockups. Use your preferred network.
            </div>
          </div>
        </div>
      </div>
    );
  };

  const renderStep2 = (): React.JSX.Element => {
    if (!selectedToken) {
      return <div>No token selected</div>;
    }

    return (
      <div className="flex flex-col gap-4">
        <div className="flex flex-col text-center">
          <div className="text-espresso text-(length:--body-super-comfortable) font-bold font-['InterRegular'] leading-[1.4]">
            Earn 3.56% APY
          </div>
          <div className="self-stretch text-clay-light text-(length:--body-small) font-medium font-['InterRegular'] leading-[1.4]">
            Takes ~10 seconds
          </div>
        </div>
        <div className="flex justify-center">
          <TokenAsset
            name={selectedToken.symbol || ''}
            token={selectedToken}
            isHoldToken={true}
            formattedBalance={'0.01'}
            isGroup={false}
            isClickBlurred={false}
            isHoverDimmed={false}
            isHovered={false}
            onMouseEnter={() => {}}
            onMouseLeave={() => {}}
            onClick={() => {}}
          />
        </div>
      </div>
    );
  };

  const renderStep3 = (): React.JSX.Element => {
    return (
      <div className="flex flex-col gap-6">
        <div className="text-center">
          <p className="text-clay font-['InterRegular'] text-(length:--body-comfortable) leading-relaxed">
            Approval confirmed. You can now proceed with the deposit.
          </p>
        </div>
      </div>
    );
  };

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent
        className="w-full md:!max-w-[480px] p-8 md:p-12 pb-8 gap-0 sm:h-86 bg-vibrant-white"
        hideCloseButton={true}
      >
        <DialogTitle className="flex w-full justify-end h-4 relative p-0">
          <XIcon
            className="w-4 h-4 cursor-pointer text-clay-light hover:text-clay absolute top-0 "
            onClick={handleClose}
          />
        </DialogTitle>
        {currentStep === 1 && renderStep1()}
        {currentStep === 2 && renderStep2()}
        {currentStep === 3 && renderStep3()}
        <DialogFooter className="flex justify-between mt-8">
          <Button
            variant="cherry"
            className="text-white font-['InterRegular'] w-[188px]"
            onClick={handleContinue}
            disabled={currentStep !== 1}
          >
            Continue
          </Button>
          <Button
            variant="cherry"
            className="text-white font-['InterRegular'] w-[40px]"
            onClick={handleApprove}
            disabled={currentStep !== 2 || !supplyBalance || Number.parseFloat(supplyBalance) <= 0 || isApproving}
          >
            {currentStep === 1 ? <FilePenLine /> : isApproving ? 'Approving...' : 'Approve'}
          </Button>
          <Button
            variant="cherry"
            className="text-white font-['InterRegular'] w-[140px]"
            onClick={handleDeposit}
            disabled={currentStep !== 3}
          >
            Deposit
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
