import type { ChainId, IntentRelayChainId } from '../chain/index.js';

// chain ids (actual for evm chains), custom for other chains not having native ids
export const AVALANCHE_MAINNET_CHAIN_ID = '0xa86a.avax';
export const ARBITRUM_MAINNET_CHAIN_ID = '0xa4b1.arbitrum';
export const BASE_MAINNET_CHAIN_ID = '0x2105.base';
export const BSC_MAINNET_CHAIN_ID = '0x38.bsc';
export const INJECTIVE_MAINNET_CHAIN_ID = 'injective-1';
export const SONIC_MAINNET_CHAIN_ID = 'sonic';
export const ICON_MAINNET_CHAIN_ID = '0x1.icon';
export const SUI_MAINNET_CHAIN_ID = 'sui';
export const OPTIMISM_MAINNET_CHAIN_ID = '0xa.optimism';
export const POLYGON_MAINNET_CHAIN_ID = '0x89.polygon';
export const SOLANA_MAINNET_CHAIN_ID = 'solana';
export const STELLAR_MAINNET_CHAIN_ID = 'stellar';
export const NIBIRU_MAINNET_CHAIN_ID = 'nibiru';

// currently supported spoke chains
export const SPOKE_CHAIN_IDS = [
  AVALANCHE_MAINNET_CHAIN_ID,
  ARBITRUM_MAINNET_CHAIN_ID,
  BASE_MAINNET_CHAIN_ID,
  BSC_MAINNET_CHAIN_ID,
  INJECTIVE_MAINNET_CHAIN_ID,
  SUI_MAINNET_CHAIN_ID,
  OPTIMISM_MAINNET_CHAIN_ID,
  POLYGON_MAINNET_CHAIN_ID,
  SOLANA_MAINNET_CHAIN_ID,
  ICON_MAINNET_CHAIN_ID,
  STELLAR_MAINNET_CHAIN_ID,
  NIBIRU_MAINNET_CHAIN_ID,
] as const;

export const HUB_CHAIN_IDS = [SONIC_MAINNET_CHAIN_ID] as const;

export const CHAIN_IDS = [
  AVALANCHE_MAINNET_CHAIN_ID,
  ARBITRUM_MAINNET_CHAIN_ID,
  BASE_MAINNET_CHAIN_ID,
  BSC_MAINNET_CHAIN_ID,
  INJECTIVE_MAINNET_CHAIN_ID,
  SONIC_MAINNET_CHAIN_ID,
  SUI_MAINNET_CHAIN_ID,
  OPTIMISM_MAINNET_CHAIN_ID,
  POLYGON_MAINNET_CHAIN_ID,
  SOLANA_MAINNET_CHAIN_ID,
  ICON_MAINNET_CHAIN_ID,
  STELLAR_MAINNET_CHAIN_ID,
  NIBIRU_MAINNET_CHAIN_ID,
] as const;

export const EVM_CHAIN_IDS = [
  AVALANCHE_MAINNET_CHAIN_ID,
  ARBITRUM_MAINNET_CHAIN_ID,
  BASE_MAINNET_CHAIN_ID,
  BSC_MAINNET_CHAIN_ID,
  SONIC_MAINNET_CHAIN_ID,
  OPTIMISM_MAINNET_CHAIN_ID,
  POLYGON_MAINNET_CHAIN_ID,
  NIBIRU_MAINNET_CHAIN_ID,
] as const;

export const EVM_SPOKE_CHAIN_IDS = [
  AVALANCHE_MAINNET_CHAIN_ID,
  ARBITRUM_MAINNET_CHAIN_ID,
  BASE_MAINNET_CHAIN_ID,
  BSC_MAINNET_CHAIN_ID,
  OPTIMISM_MAINNET_CHAIN_ID,
  POLYGON_MAINNET_CHAIN_ID,
  NIBIRU_MAINNET_CHAIN_ID,
] as const;

// NOTE: This is not the same as the actual chain ids (wormhole based ids), only used for intent relay
export const INTENT_RELAY_CHAIN_IDS = {
  AVAX: 6n,
  SUI: 21n,
  SONIC: 146n,
  STELLAR: 27n,
  INJ: 19n,
  SOL: 1n,
  ICON: 1768124270n,
  ARCHWAY: 1634886504n,
  BASE: 30n,
  BINANCE: 4n,
  OPTIMISM: 24n,
  POLYGON: 5n,
  ARBITRUM: 23n,
  NIBIRU: 7235938n,
} as const;

export const ChainIdToIntentRelayChainId: Record<ChainId, IntentRelayChainId> = {
  [AVALANCHE_MAINNET_CHAIN_ID]: INTENT_RELAY_CHAIN_IDS.AVAX,
  [ARBITRUM_MAINNET_CHAIN_ID]: INTENT_RELAY_CHAIN_IDS.ARBITRUM,
  [BASE_MAINNET_CHAIN_ID]: INTENT_RELAY_CHAIN_IDS.BASE,
  [BSC_MAINNET_CHAIN_ID]: INTENT_RELAY_CHAIN_IDS.BINANCE,
  [INJECTIVE_MAINNET_CHAIN_ID]: INTENT_RELAY_CHAIN_IDS.INJ,
  [SONIC_MAINNET_CHAIN_ID]: INTENT_RELAY_CHAIN_IDS.SONIC,
  [OPTIMISM_MAINNET_CHAIN_ID]: INTENT_RELAY_CHAIN_IDS.OPTIMISM,
  [POLYGON_MAINNET_CHAIN_ID]: INTENT_RELAY_CHAIN_IDS.POLYGON,
  [SOLANA_MAINNET_CHAIN_ID]: INTENT_RELAY_CHAIN_IDS.SOL,
  [SUI_MAINNET_CHAIN_ID]: INTENT_RELAY_CHAIN_IDS.SUI,
  [STELLAR_MAINNET_CHAIN_ID]: INTENT_RELAY_CHAIN_IDS.STELLAR,
  [ICON_MAINNET_CHAIN_ID]: INTENT_RELAY_CHAIN_IDS.ICON,
  [NIBIRU_MAINNET_CHAIN_ID]: INTENT_RELAY_CHAIN_IDS.NIBIRU,
};
