name: Publish @sodax/dapp-kit Package to npmjs

on:
  push:
    tags:
      - '@sodax/dapp-kit@*.*.*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.8.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build Packages
        run: pnpm build:packages
      - name: Publish package
        run: |
          cd packages/dapp-kit
          pnpm publish --no-git-checks --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.SODAX_FRONTEND_NPM_TOKEN}}